language: python
python:
  - "2.7"
  # - "3.2"
install:
  - pip install . --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - coverage run -m unittest discover
after_success:
  - coveralls -c coverage.rc
